name: the_list
description: "A productivity app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.3
  flutter_datetime_picker: ^1.5.1
  flutter_slidable: ^3.1.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
