name: the_list
description: "A productivity app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.3
  flutter_datetime_picker: ^1.5.1
  flutter_slidable: ^3.1.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  flutter_native_splash: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.14.1

# custom launcher icon
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_foreground: "assets/images/app_logo.png" # Set the foreground image (same or different from image_path)
  adaptive_icon_background: "#1E1E2F"
  min_sdk_android: 21 # android min sdk min:16, default 21

# custom splash screen
flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#1E1E2F"
  image: "assets/images/splash_screen_image.png"

  android_12:
    color: "#1E1E2F"
    image: "assets/images/splash_screen_image.png"



flutter:
  uses-material-design: true
